import React, { useEffect, useState } from 'react'
import axios from "axios"

export default function Datauploader() {
//     const name=[
//       "Red Chilli Powder	",
//       "Red Chilli Powder	",
//       "Turmeric Powder	",
//       "Turmeric Powder	",
//       "Coriander Powder	",
//       "Coriander Powder	",
//       "Cumin Seeds	",
//       "Cumin Seeds	",
//       "Fennel	",
//       "Fennel	",HEAD
//       "Rock Salt	",
//       "Rock Salt	",
//       "Carom Seeds	",
//       "Carom Seeds	",
//       "Mustard Seeds	",
//       "Mustard Seeds	",
//       "Black Salt	",
//       "Black Salt	",
//       "Fenugreek	",
//       "Fenugreek	",
//       "Coriander Whole	",
//       "Coriander Whole	",
//       "White Sesame	",
//       "White Sesame	",
//       "Peanut Oil	",
//       "Peanut Oil	",
//       "Coconut Oil	",
//       "Coconut Oil	",
//       "Sesame Oil	",
//       "Sesame Oil	",
//       "Mustard Oil	",
//       "Mustard Oil	",
//       "Almond Oil	",
//       "Khand Sugar	",
//       "Khand Sugar	",
//       "Jaggery Whole	",
//       "Jaggery Powder	",
//       "Jaggery Powder	",
//       "Bajra	",
//       "Makka	",
//       "jwar	",
//       "Ragi	",
//       "Bansi Wheat	",
//       "Sharbati Wheat	",
//       "Black Wheat	",
//       "Govind Bhog Rice	",
//       "Brown Rice	",
//       "/Premium Basmati Rice	",
//       "Kabuli Chana	",
//       "Kabuli Chana	",
//       "Kala Chana	",
//       "Kala Chana	",
//       "Peanuts	",
//       "Peanuts	",
//       "दͧलया शरबती गेह	",
//       "दͧलया ु बसं ी गेह	",
//       "Moong Dal (छलका	",
//       "Moong Dal (छलका	",
//       "Moong Dal (मोगर) ",
//       "Moong Dal (मोगर)	",
//       "Toor dal मशीन से बनी हुई	",
//       "Toor dal मशीन से बनी हुई)	",
//       "Toor dal (घɪटȣ मे पीसी हुई)	",
//       "Toor dal (घɪटȣ मे पीसी हुई)	",
//       "Urad Dal	",
//       "Urad Dal	",
//       "Chana Dal	",
//       "Chana Dal	",
//       "Moong Whole	",
//       "Moong Whole	",
//       "Urad Whole	",
//       "Urad Whole	",
//       "Chia Seeds	",
//       "Chia Seeds	",
//       "Masoor Whole	",
//       "Masoor Whole	",
//       "Jwar Flour 	",
//       "Ragi Flour	",
//       "Bajra Flour	",
//       "Bansi Wheat Flour	",
//       "Sharbati Wheat Flour	",
//       "Gram Flour	",
//       "Gram Flour	",
//       "Black Wheat Flour	",
//       "Combo Pack of 5 Shridhanya Millets	",
//       "Combo Pack of 5 Shridhanya Millets	",
//       "Combo pack of 5 Shridhanya Millets Flour	",
//       "Combo pack of 5 Shridhanya Millets Flour	",
//       "Pure A2 Deshi Bilona Ghee	",
//       "Pure A2 Deshi Bilona Ghee	",
//       "Date Palm Jaggery	",
//       "Date Palm Jaggery	",
//       "Ragi Kaju Pista Laddu	",
//       "Ragi Badam Kaju Laddu	",
//       "Ragi Badam peanut Laddu	",
//       "Ragi Anjeer Kaju Laddu	",
//       "Ragi Walnut Magaj Laddu	",
//       "Ragi Alsi Badam Peanut Laddu	",
//       "Ragi Choco Bits	",
//       "Ragi Gond & Mixed Nuts Laddu 	",
//       "Millets Kaju Pista Laddu	",
//       "Millets Badam Kaju Laddu	",
//       "Millets Badam peanut Laddu	",
//       "Millets Anjeer Kaju Laddu	",
//       "Millets Walnut Magaj Laddu	",
//       "Millets Gond & Mixed Nuts Laddu	",
//       "Besan Laddu	",
//       "Ragi Kaju Pista Laddu	",
//       "Ragi Badam Kaju Laddu	",
//       "Ragi Badam peanut Laddu	",
//       "Ragi Anjeer Kaju Laddu	",
//       "Ragi Walnut Magaj Laddu	",
//       "Ragi Alsi Badam Peanut Laddu	",
//       "Ragi Choco Bits	",
//       "Ragi Gond & Mixed Nuts Laddu 	",
//       "Millets Kaju Pista Laddu	",
//       "Millets Badam Kaju Laddu	",
//       "Millets Badam peanut Laddu	",
//       "Millets Anjeer Kaju Laddu	",
//       "Millets Walnut Magaj Laddu	",
//       "Millets Gond & Mixed Nuts Laddu	",
//       "Besan Laddu	",
//       "Ragi Millet Snacks	",
//       "Bajra Millet Snacks	",
//       "Jowar Millet Snacks	",
//       "Ujjaini Sev	",
//       "Ratlami Sev	",
//       "Laung Sev	",
//       "Mitha mixture	",
//       "Tikha Mixture	",
//       "Fiki Barik Sev	",
//       "Fiki Besan Papdi	",
//       "Ujjaini Sev	",
//       "Ratlami Sev	",
//       "Laung Sev	",
//       "Mitha mixture	",
//       "Tikha Mixture	",
//       "Fiki Barik Sev	",
//       "Fiki Besan Papdi	",
//       "Ujjaini Sev	",
//       "Ratlami Sev	",
//       "Laung Sev	",
//       "Mitha mixture	",
//       "Tikha Mixture	",
//       "Fiki Barik Sev	",
//       "Fiki Besan Papdi	",
//     ]
//     const price=[75	,
//       150	,
//       75	,
//       150	,
//       65	,
//       130	,
//       90	,
//       180	,
//       65	,
//       130	,
//       40	,
//       80	,
//       65	,
//       130	,
//       30	,
//       60	,
//       40	,
//       80	,
//       30	,
//       60	,
//       55	,
//       110	,
//       100	,
//       195	,
//       260	,
//       1275	,
//       200	,
//       390	,
//       380	,
//       1875	,
//       280	,
//       1375	,
//       250	,
//       55	,
//       100	,
//       100	,
//       60	,
//       110	,
//       60	,
//       55	,
//       60	,
//       60	,
//       275	,
//       260	,
//       300	,
//       150	,
//       120	,
//       160	,
//       75	,
//       145	,
//       65	,
//       130	,
//       95	,
//       195	,
//       60	,
//       70	,
//       70	,
//       140	,
//       75	,
//       145	,
//       75	,
//       150	,
//       100	,
//       190	,
//       70	,
//       135	,
//       70	,
//       130	,
//       65	,
//       130	,
//       65	,
//       125	,
//       100	,
//       200	,
//       65	,
//       125	,
//       80	,
//       80	,
//       80	,
//       300	,
//       275	,
//       80	,
//       150	,
//       325	,
//       350	,
//       650	,
//       425	,
//       800	,
//       800	,
//       1600	,
//       200	,
//       380	,
//       610	,
//       560	,
//       520	,
//       585	,
//       565	,
//       530	,
//       575	,
//       590	,
//       585	,
//       535	,
//       495	,
//       560	,
//       540	,
//       540	,
//       545	,
//       1070	,
//       975	,
//       895	,
//       1020	,
//       980	,
//       910	,
//       1005	,
//       1035	,
//       1020	,
//       925	,
//       845	,
//       970	,
//       930	,
//       930	,
//       940	,
//       45	,
//       45	,
//       45	,
//       90	,
//       90	,
//       90	,
//       90	,
//       90	,
//       85	,
//       85	,
//       180	,
//       180	,
//       180	,
//       180	,
//       180	,
//       170	,
//       170	,
//       350	,
//       350	,
//       350	,
//       350	,
//       350	,
//       330	,
//       330	]
// const category=[
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Spices"	,
//   "Cold Pressed Oil"	,
//   "Cold Pressed Oil"	,
//   "Cold Pressed Oil"	,
//   "Cold Pressed Oil"	,
//   "Cold Pressed Oil"	,
//   "Cold Pressed Oil"	,
//   "Cold Pressed Oil"	,
//   "Cold Pressed Oil"	,
//   "Cold Pressed Oil"	,
//   "Sweetner"	,
//   "Sweetner"	,
//   "Sweetner"	,
//   "Sweetner"	,
//   "Sweetner"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Cereals"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Pulses"	,
//   "Flour"	,
//   "Flour"	,
//   "Flour"	,
//   "Flour"	,
//   "Flour"	,
//   "Flour"	,
//   "Flour"	,
//   "Flour"	,
//   "Special"	,
//   "Special"	,
//   "Special"	,
//   "Special"	,
//   "Special"	,
//   "Special"	,
//   "Special"	,
//   "Special"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Desserts"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
//   "Healthy Snacks"	,
// ]

// const quantity=[
//   250	,
// 500	,
// 250	,
// 500	,
// 250	,
// 500	,
// 250	,
// 500	,
// 250	,
// 500	,
// 500	,
// 1	,
// 250	,
// 500	,
// 250	,
// 500	,
// 500	,
// 1	,
// 250	,
// 500	,
// 250	,
// 500	,
// 500	,
// 1	,
// 1	,
// 5	,
// 500	,
// 1	,
// 1	,
// 5	,
// 1	,
// 5	,
// 100	,
// 500	,
// 1	,
// 1	,
// 500	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 5	,
// 5	,
// 5	,
// 1	,
// 1	,
// 1	,
// 500	,
// 1	,
// 500	,
// 1	,
// 500	,
// 1	,
// 1	,
// 1	,
// 500	,
// 1	,
// 500	,
// 1	,
// 500	,
// 1	,
// 500	,
// 1	,
// 500	,
// 1	,
// 500	,
// 1	,
// 500	,
// 1	,
// 500	,
// 1	,
// 500	,
// 1	,
// 500	,
// 1	,
// 1	,
// 1	,
// 1	,
// 5	,
// 5	,
// 500	,
// 1	,
// 5	,
// 2.5	,
// 5	,
// 2.5	,
// 5	,
// 500	,
// 1	,
// 500	,
// 1	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 100	,
// 100	,
// 100	,
// 250	,
// 250	,
// 250	,
// 250	,
// 250	,
// 250	,
// 250	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 500	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	,
// 1	
// ]
// const unit=[
//   "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "kg",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "kg",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "kg",
// "lit",
// "lit",
// "ml",
// "lit",
// "lit",
// "lit",
// "lit",
// "lit",
// "ml",
// "gm",
// "kg",
// "kg",
// "gm",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// "gm",
// "kg",
// "gm",
// "kg",
// "gm",
// "kg",
// "kg",
// "kg",
// "gm",
// "kg",
// "gm",
// "kg",
// "gm",
// "kg",
// "gm",
// "kg",
// "gm",
// "kg",
// "gm",
// "kg",
// "gm",
// "kg",
// "gm",
// "kg",
// "gm",
// "kg",
// "gm",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// "gm",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// "ml",
// "lit",
// "gm",
// "kg",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "Kg",
// "Kg",
// "Kg",
// "Kg",
// "Kg",
// "Kg",
// "Kg",
// "Kg",
// "Kg",
// "Kg",
// "Kg",
// "Kg",
// "Kg",
// "Kg",
// "Kg",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "gm",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// "kg",
// ]
const name = ["A2 Dry Milk Powder ",
"Aloevera Hair Shampoo ",
"Aloevera Panchgavya Bath Soap ",
"Aloevera Pure Juice ",
"Brahmi Amla    ",
"Chandan Panchgavya Bath Soap ",
"Dish Wash Gel ",
"Face Wash ",
"Floor cleaner ",
"Gau Amrit Milk Kesar Bath Soap ",
"Go Real Neem & Cow Urine Bath Soap ",
"Gopika Panchgavya Bath Soap ",
"Hand Wash Liquid ",
"Jasmine Panchgavya Bath Soap ",
"Panchgavya Moisturizing Body Lotion ",
"Toilet Cleaner ",
"Ubtan - Ayurvedic Bath Powder ",
"Tulsi Honey ",
"Rooswood Honey ",
"Wild Forest ",
"Jamun Honey",
"Litchi Honey ",
"Sider Honey ",
" Carbon Panchgavya Bath Soap "];

  const price=[80,85,60,110,100,55,85,70,40,70,30,55,105,45,75,85,50,280,255,250,360,280,280,55 ];
  const unit=["gm","ml","gm","ml","ml","gm","ml","gm","ml","gm","gm","gm","ml","gm","ml","ml","gm","gm","gm","gm","gm","gm","gm","gm" ]
  const quantity = [100,100,75,500,100,75,250,50,500,75,65,75,250,75,100,500,100,400,400,400,400,400,400,75];
  const image =[
    "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2Fgir-cow-a2-dry-milk-100g.jpg?alt=media&token=acce008a-a137-4a89-92a3-ae60d7347111		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2FAlovera%20Shampoo.png?alt=media&token=61ca2601-8579-4dbe-a27b-753a5b8a8ca1		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2FAlovera%20Soap.png?alt=media&token=699eee2c-c9a1-4449-ae2d-b3b2c434cc9c		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2FAloevera%20Juice.png?alt=media&token=4354e4de-e4b0-4eb3-89ab-07714a63aaec		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2FBrahami%20Amla%20Oil.png?alt=media&token=6e0a109a-b625-4e75-a25c-0b1f02b596a0		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2FChandan%20Soap.png?alt=media&token=d85f26b2-caac-4968-86c6-e330ad0b6184		",
  "https://gosevaonline.com/		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2FFacewash.png?alt=media&token=28341f94-a2c4-4727-81c2-5181aaa84c0b		",
  "https://gosevaonline.com/		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2FGo%20Amrit.png?alt=media&token=f6860512-e663-47b9-8b02-4833e993a85a		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2FGo%20Real%20Soap.png?alt=media&token=021542f3-cd81-46e3-b2c8-1f655ae0dd9a		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2FGopika.png?alt=media&token=c092e8ef-e387-415d-bc58-347253f4f360		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2FHand%20Wash.png?alt=media&token=75bd625a-7050-4c1c-b7bf-e536e9be5cfa		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2FJasmin%20Soap.png?alt=media&token=35d1ec39-55a3-44f5-b811-1b9067cd5bad		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2Fpanchagavya-skin-lotion.jpg?alt=media&token=856be9d1-6889-427f-9212-025b599e6756		",
  "https://gosevaonline.com/	",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2FUbtan.png?alt=media&token=02834ac8-45f7-481f-82cb-622d467a58dc		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2F37.png?alt=media&token=e8d97800-0b95-4990-ac7d-2c4ce8284347		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2F35.png?alt=media&token=c1eb67b8-7907-473e-bd64-4889b7730ee1		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2F38.png?alt=media&token=254bfdc9-fc80-42a8-b24b-e4eb2407a6b7		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2F33.png?alt=media&token=a8e75e29-e83a-4ead-bf6b-7fc4831e9ec1		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2F34.png?alt=media&token=fbee4ff6-4ab2-4056-a0dc-d275acb7dd2d		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2F36.png?alt=media&token=f5f9fbaf-e730-452d-89dd-1e3f584f0dae		",
  "https://firebasestorage.googleapis.com/v0/b/savornaturals-911a0.appspot.com/o/Goseva%2FCarbon%20Soap.png?alt=media&token=ab9c3860-3460-4ed2-bf88-fcfa86f0765a		"]
  const description =["One of the best Milk Powder by GoSeva is prepared using Gir Cow's A2 Milk, hygienically packed with no preservatives. GoSeva A2 Cow Milk Powder is made from 100% pure & delicious fresh gir cows milk grazes in organic natural land of Gujarat, India. Goseva ensures zero chemical process intervention during entire manufacturing process.",
  "GoSeva Aloe Vera Hair Shampoo has all the benefits of an Organic Shampoo. Wash your hair with Goseva Aloe Vera Shampoo and experience the best ever hair wash. The natural ingredients in aloe vera helps in nourishing your hair roots and reduces hair fall significantly. This Shampoo is useful in dryness & roughness of hair. Aloe Vera Shampoo prevents hair fall and improves hair strength.",
  "Goseva Aloe vera soap is both mild and 100% natural product. It contains Panchagavya elements.",
"Natural Aloevera Juice with FIBER CONTENT is effective in reducing weight, boosting body’s immunity, combating all kinds of microbial infections, aids in digestion and functions as anti inflammatory as well as anti allergen agent. It is good for all types of skin and proves a boon for sensitive facial skins with acne problems.",
"Bramhi is very useful in curing central nervous system diseases. It acts as a brain tonic and increases memory. Amla nourishes your hair and make them long and strong. The combination of Bramhi & Amla oil removes dandruff from scalp and solves head skin disease problem.",
"It is made from Gir cow’s Ghee (Panchagavya), Cow’s Milk (Panchagavya), GoMaya (Panchagavya), Chandan Powder, aloe vera , glycerine, sandalwood Oil and Ayurvedic soap Base. Goseva Chandan Soap is all set to impart smoothness, removes rashes, fight infecting agents, acnes and cures eruptions. The mild aroma of sandalwood fights body odor and gives your skin a healthy look.",
"Goseva believes that naturally derived dish wash cleaners should be accessible, effective and affordable for everyone. Goseva product combines powerful cleaning performance with naturally derived and plant-based ingredients. This naturally derived dish wash liquid helps you remove tough stains easily. This Dish Wash does not conatin phosphorus and bleach contents to ensure zero adverse effect on skin.",
"Concocted from Mix Fruit extract, Apple extract, Banana extract,, Pineapple extract. Black Berries extract, Lemon extract, Cucumber extract, Grape Seed extract, Peach extract, Aloevera extract, Soya Protein extract, Face Wash Soft Base; this preparation is meant for removing impurities from skin pores that block them and result in pimples and acne on the otherwise beautiful face. The alovera with its antibacterial properties removes any possibility of having skin infections. The fruit extracts freshens and rejuvenates the dry skin.",
"Most of the commercial floor cleaners available today, contain toxins and poisons that are hazardous to human health. Warning labels on these products themselves state that the contents are poisonous or dangerous, as they are chemical in origin. Even when stored carefully, toxic floor cleansers can leak out of bottles or be inhaled during use, especially dangerous in households with children. These toxic products seep into the environment, contaminating water supplies. No doubt theses cleaning products containing disinfectants can kill germs immediately but may also contribute to their stronger resistance in the long run.",
"Formulated with natural moisturisers like coconut oil, palm oil and 10% Cow’s milk by weight and saffron the soap will keep your skin healthier and softer. The selection of finest ingredients in making of Gau Amrit protects your sensitive skin from dyes, synthetic preservatives and artificial fragrance used commonly to manufacture commercial soaps. Pamper your skin with Gau Amrit milk kesar soap. It is the only natural and fairness soap, manufactured first time in India from the milk of indigenous breed of Indian Cow. The combination of milk and saffron is the most beneficial for your skin’s health. ",
"GoSeva GoReal Anti Bacterial Neem Soap is a natural Panchagavya bath soap with neem prepared with Indian Cow Urine. Cow's urine in this Neem soap is said to have many healthy properties. This herbal bath soap contains the essence of cow's urine and has super Anti-bacterial properties. NO ANIMAL FAT",
"Gopika Panchagavya soap is a natural & organic soap. There are very few natural soap manufacturers in India these days that use Panchagavya. This soap brightens the skin and makes it fresh. Panchagavya contains five important cow products like [cow urine, cow milk, cow dung, cow ghee and curd .The Indian Gir cow (and also other indigenous breeds) has a hump on it’s back. Nevertheless, the significance of this hump is that a vein known as ‘Surya Ketu nadi’ passes through them. The Surya Ketu Nadi on interaction with Sun’s rays produce gold salts in the cow’s blood. These salts are present in the cow’s milk, urine and dung, which miraculously cure many diseases.",
"Goseva Panchagavya Neem Extracts Hand Wash has Gojharan (Gomutra) with Anti-Bacterial properties. Neem leaf, bark extracts, neem oil & go mutra are known to suppress several pathogenic bacterial species, it's anti-viral activities against vaccinia, chikungunya, measles virus and Coxsackie B viruses and antifungal activities against sevaral human fungi havebeen established. Anti bacterial properties improves skin barrier function.",
"If you are a fragrance lover and wish that you smell like fresh flowers after taking bath in the mornings and evenings then Goseva brings you the all new Jasmine Panchagavya Bath Soap endowed with the qualities as well as natural fragrance of Jasmine flowers. Designed and Manufactured with Jasmine Extracts, Cow’s Ghee (Panchgavya), Cow’s milk (Panchgavya), GoMaya (Panchgavya), Jasmine Oil, aloe vera and Ayurvedic soap Base. This wonderful soap renders refreshed and rejuvenated skin which gives soft feel and glowing effect. The aloe vera detoxifies and rejuvenates dead and dull skin. The cow’s milk and ghee impart smoothness and rash free healthy skin.",
"The lotion is blended with the extracts of Aloe Vera, Natural Vitamin E, Cow Milk and Pure Cow Ghee with Honey and Cow Urine Ark, which protects your skin from pollution & uncertain weather. It provides nourishment your skin and restores moisture. It helps you to repair your dead skins and prevent from skin infections.",
"GoSeva EcoFresh Toilet Cleaner comes with the advantage of Cow Urine and Neem Extract which makes it one of the natural yet powerful toilet cleaner ever. Maintains hygiene in every wash with last long fragrance.",
"Ubtan is used in India from ancient times during festivals and during auspicious occasions. Ubtan is an anti-bacterial powder that enhances skin glow and makes your face look fresh. Ubtan Powder protects the skin from leprosy, cirrhosis, and other skin diseases.",
"Tulsi, undeniably one of the most widely revered herbs in Ayurvedic medicine, has incomparable benefits. Rich in natural healing agents like vitamins, minerals, and other phytonutrients, tulsi is said to act as an adaptogen. It doesn't just treat the diseases but is also said to compensate for the aging process and impart a sense of calmness and positivity.",
" Natural,non-processed Full of nutrition Boosts stamina Relieves stress and depression Boosts memory",
" Full of natural and medicinal qualities Healing wounds Boosts memory  Helps reduce gum problems Helps improve immunity",
"About This Item: Enriched with vitamins and minerals Fit for diabetic patientsGives a soothing calming feelingHigh in Vitamin C",
"Enriched with natural flavour No added preservatives/colours Non pasteurised Chemical free Can be used as a substitute for sugar",
"Healing post surgical wounds Respiratory infections Stomach ulcers Eye problems Gynec ailments in women Epilepsy Boosts immunity and vitality",
"Goseva Carbon Soap is 100% natural Panchagavya product. It’s manufactured especially to deal with skin problems like acne, psoriasis and oily skin. The carbon content is an added advantage to those who live in highly polluted cities and metros. The carbon absorbs all the suspended particles which block the pores of the skin and makes it appear dead & dull."
]

  var i=0;

    const callapi=async ()=>{
        await axios.post("/product/addproduct",{images:[{imgUrl:image[i]}],name:name[i],  description:description[i], price:price[i], stock:20,  category:"Goseva", feature:false,rating:0,reviews:0, quantity:quantity[i],unit:unit[i]})
        .then((res) => {
            i++;
            console.log(i);
            if(i<24){
                callapi();
            }
        //  alert("Products has been added")
        })
    }
    useEffect(() => {
      // callapi();
    }, [])
    
  return (
    <div>Data Was uploaded</div>
  )
}


